import type { ActivityLog, Category, Comment, Notification, Ticket, User } from "./types";

export const users: User[] = [
  {
    id: "u-pegawai-1",
    username: "rina",
    password: "password123",
    name: "Rina Wulandari",
    email: "rina@pemda.go.id",
    role: "PEGAWAI",
    unit: "Dinas Kependudukan",
    phone: "0812-1100-2211",
    createdAt: "2026-05-12T08:00:00.000Z",
  },
  {
    id: "u-pegawai-2",
    username: "budi",
    password: "password123",
    name: "Budi Santoso",
    email: "budi@pemda.go.id",
    role: "PEGAWAI",
    unit: "Dinas Kesehatan",
    createdAt: "2026-05-16T08:00:00.000Z",
  },
  {
    id: "u-teknisi-1",
    username: "andika",
    password: "password123",
    name: "Andika Pratama",
    email: "andika.it@pemda.go.id",
    role: "TEKNISI",
    unit: "Tim Infrastruktur",
    phone: "0813-7777-1001",
    createdAt: "2026-04-20T08:00:00.000Z",
  },
  {
    id: "u-teknisi-2",
    username: "sari",
    password: "password123",
    name: "Sari Lestari",
    email: "sari.sec@pemda.go.id",
    role: "TEKNISI",
    unit: "Tim Keamanan Informasi",
    createdAt: "2026-04-22T08:00:00.000Z",
  },
  {
    id: "u-admin-1",
    username: "admin",
    password: "admin123",
    name: "Maya Kartika",
    email: "admin.sihati@pemda.go.id",
    role: "ADMIN",
    unit: "UPT Layanan TIK",
    createdAt: "2026-04-18T08:00:00.000Z",
  },
  {
    id: "u-pimpinan-1",
    username: "pimpinan",
    password: "pimpinan123",
    name: "Drs. Hendra Wijaya",
    email: "kadis@pemda.go.id",
    role: "PIMPINAN",
    unit: "Kepala Dinas Kominfo",
    createdAt: "2026-04-10T08:00:00.000Z",
  },
];

export const categories: Category[] = [
  {
    id: "cat-network",
    name: "Jaringan & MikroTik",
    description: "Gangguan koneksi, VLAN, firewall, routing, dan perangkat jaringan.",
    ownerTeam: "Tim Infrastruktur",
  },
  {
    id: "cat-cloud",
    name: "Cloud & Server",
    description: "Konfigurasi VM, storage, backup, sertifikat, dan layanan cloud.",
    ownerTeam: "Tim Infrastruktur",
  },
  {
    id: "cat-security",
    name: "Keamanan Informasi",
    description: "Akun mencurigakan, akses tidak sah, hardening, dan audit insiden.",
    ownerTeam: "Tim Keamanan Informasi",
  },
  {
    id: "cat-hardware",
    name: "Hardware",
    description: "PC, printer, scanner, UPS, dan perangkat kerja pegawai.",
    ownerTeam: "Tim Layanan Perangkat",
  },
  {
    id: "cat-app",
    name: "Aplikasi Internal",
    description: "Aplikasi dinas, SSO, integrasi, dan kendala transaksi layanan.",
    ownerTeam: "Tim Aplikasi",
  },
];

export const initialTickets: Ticket[] = [
  {
    id: "t-001",
    code: "TK-001",
    title: "Jaringan MikroTik lantai 3 tidak stabil",
    description:
      "Koneksi pegawai sering terputus sejak pagi. Aplikasi pelayanan menjadi lambat saat mengakses server internal.",
    priority: "CRITICAL",
    status: "IN_PROGRESS",
    categoryId: "cat-network",
    reporterId: "u-pegawai-1",
    assigneeId: "u-teknisi-1",
    location: "Gedung A Lt. 3",
    slaDueAt: "2026-06-05T13:30:00.000Z",
    createdAt: "2026-06-05T08:40:00.000Z",
    updatedAt: "2026-06-05T10:20:00.000Z",
    attachments: [
      {
        id: "a-001",
        ticketId: "t-001",
        name: "capture-ping.png",
        url: "#",
        fileType: "image/png",
        size: "340 KB",
        createdAt: "2026-06-05T08:43:00.000Z",
      },
    ],
  },
  {
    id: "t-002",
    code: "TK-002",
    title: "Error konfigurasi security group cloud",
    description:
      "Aplikasi perizinan tidak dapat menerima callback dari gateway pembayaran setelah perubahan rule keamanan.",
    priority: "HIGH",
    status: "ASSIGNED",
    categoryId: "cat-cloud",
    reporterId: "u-pegawai-2",
    assigneeId: "u-teknisi-2",
    location: "Dinas Kesehatan",
    slaDueAt: "2026-06-05T15:00:00.000Z",
    createdAt: "2026-06-05T09:05:00.000Z",
    updatedAt: "2026-06-05T09:30:00.000Z",
    attachments: [],
  },
  {
    id: "t-003",
    code: "TK-003",
    title: "Printer pelayanan tidak terdeteksi",
    description:
      "Printer loket 2 tidak muncul di daftar perangkat setelah pergantian router ruangan.",
    priority: "MEDIUM",
    status: "OPEN",
    categoryId: "cat-hardware",
    reporterId: "u-pegawai-1",
    location: "Mall Pelayanan Publik",
    slaDueAt: "2026-06-06T09:00:00.000Z",
    createdAt: "2026-06-05T09:28:00.000Z",
    updatedAt: "2026-06-05T09:28:00.000Z",
    attachments: [],
  },
  {
    id: "t-004",
    code: "TK-004",
    title: "Reset akses aplikasi arsip digital",
    description: "Pegawai baru belum mendapatkan akses aplikasi arsip digital dan membutuhkan akun hari ini.",
    priority: "LOW",
    status: "RESOLVED",
    categoryId: "cat-app",
    reporterId: "u-pegawai-2",
    assigneeId: "u-teknisi-1",
    location: "Sekretariat Daerah",
    slaDueAt: "2026-06-04T15:00:00.000Z",
    createdAt: "2026-06-04T10:10:00.000Z",
    updatedAt: "2026-06-04T12:00:00.000Z",
    resolvedAt: "2026-06-04T12:00:00.000Z",
    attachments: [],
  },
  {
    id: "t-005",
    code: "TK-005",
    title: "Indikasi login tidak sah pada akun operator",
    description:
      "Operator menerima notifikasi login dari lokasi asing. Mohon pemeriksaan audit dan rotasi kredensial.",
    priority: "HIGH",
    status: "PENDING",
    categoryId: "cat-security",
    reporterId: "u-pegawai-1",
    assigneeId: "u-teknisi-2",
    location: "Dinas Kependudukan",
    slaDueAt: "2026-06-05T14:30:00.000Z",
    createdAt: "2026-06-05T07:55:00.000Z",
    updatedAt: "2026-06-05T10:05:00.000Z",
    attachments: [
      {
        id: "a-005",
        ticketId: "t-005",
        name: "notifikasi-login.pdf",
        url: "#",
        fileType: "application/pdf",
        size: "190 KB",
        createdAt: "2026-06-05T08:00:00.000Z",
      },
    ],
  },
  {
    id: "t-006",
    code: "TK-006",
    title: "Scanner dokumen lambat membaca berkas",
    description: "Pemindaian dokumen kependudukan membutuhkan waktu lebih dari 2 menit per halaman.",
    priority: "MEDIUM",
    status: "CLOSED",
    categoryId: "cat-hardware",
    reporterId: "u-pegawai-1",
    assigneeId: "u-teknisi-1",
    location: "Loket Dukcapil",
    slaDueAt: "2026-06-03T16:00:00.000Z",
    createdAt: "2026-06-03T11:00:00.000Z",
    updatedAt: "2026-06-03T13:45:00.000Z",
    resolvedAt: "2026-06-03T13:20:00.000Z",
    attachments: [],
  },
];

export const initialComments: Comment[] = [
  {
    id: "c-001",
    ticketId: "t-001",
    userId: "u-pegawai-1",
    message: "Gangguan masih terjadi setelah router ruangan di-restart.",
    isInternal: false,
    createdAt: "2026-06-05T08:48:00.000Z",
  },
  {
    id: "c-002",
    ticketId: "t-001",
    userId: "u-teknisi-1",
    message: "Sedang cek log interface dan utilisasi bandwidth antar gedung.",
    isInternal: false,
    createdAt: "2026-06-05T09:25:00.000Z",
  },
  {
    id: "c-003",
    ticketId: "t-005",
    userId: "u-teknisi-2",
    message: "Internal: wajib reset MFA dan tarik audit log 24 jam terakhir.",
    isInternal: true,
    createdAt: "2026-06-05T10:05:00.000Z",
  },
];

export const notifications: Notification[] = [
  {
    id: "n-001",
    userId: "u-teknisi-1",
    title: "SLA kritikal mendekat",
    message: "TK-001 tersisa kurang dari 3 jam.",
    isRead: false,
    createdAt: "2026-06-05T10:15:00.000Z",
  },
  {
    id: "n-002",
    userId: "u-admin-1",
    title: "Antrian tiket baru",
    message: "1 tiket Open belum ditugaskan.",
    isRead: false,
    createdAt: "2026-06-05T09:35:00.000Z",
  },
  {
    id: "n-003",
    userId: "u-pimpinan-1",
    title: "Laporan SLA harian",
    message: "Compliance hari ini berada di 92%.",
    isRead: true,
    createdAt: "2026-06-05T08:00:00.000Z",
  },
];

export const weeklyTrend = [
  { day: "Sen", open: 8, resolved: 5, mttr: 3.6 },
  { day: "Sel", open: 11, resolved: 7, mttr: 3.2 },
  { day: "Rab", open: 9, resolved: 8, mttr: 2.9 },
  { day: "Kam", open: 14, resolved: 9, mttr: 3.8 },
  { day: "Jum", open: 12, resolved: 10, mttr: 3.1 },
  { day: "Sab", open: 4, resolved: 6, mttr: 2.5 },
  { day: "Min", open: 3, resolved: 4, mttr: 2.2 },
];

export const technicianPerformance = [
  { name: "Andika", resolved: 42, mttr: 3.1, sla: 94 },
  { name: "Sari", resolved: 37, mttr: 3.5, sla: 91 },
  { name: "Tim Aplikasi", resolved: 25, mttr: 4.2, sla: 86 },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: "log-001",
    userId: "u-pegawai-1",
    ticketId: "t-001",
    module: "TICKET",
    action: "CREATE_TICKET",
    description: "Membuat tiket TK-001 tentang gangguan jaringan MikroTik.",
    createdAt: "2026-06-05T08:40:00.000Z",
  },
  {
    id: "log-002",
    userId: "u-teknisi-1",
    ticketId: "t-001",
    module: "TICKET",
    action: "STATUS_UPDATE",
    description: "Mengubah status TK-001 menjadi Diproses.",
    createdAt: "2026-06-05T10:20:00.000Z",
  },
  {
    id: "log-003",
    userId: "u-teknisi-2",
    ticketId: "t-005",
    module: "COMMENT",
    action: "INTERNAL_NOTE",
    description: "Menambahkan catatan internal untuk audit keamanan TK-005.",
    createdAt: "2026-06-05T10:05:00.000Z",
  },
  {
    id: "log-004",
    userId: "u-admin-1",
    module: "USER",
    action: "ROLE_REVIEW",
    description: "Meninjau akses role teknisi dan admin pada permission matrix.",
    createdAt: "2026-06-05T09:10:00.000Z",
  },
];
